## Driver and Constructor Season Totals for the 2023 season.

In [3]:
import pandas as pd

In [4]:
driver_info = pd.read_csv('f1db_csv/drivers.csv')

In [5]:
constructor_info = pd.read_csv('f1db_csv/constructors.csv')

In [6]:
driver_info.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [7]:
constructor_info.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [17]:
driver_standings = pd.read_csv('f1db_csv/driver_standings.csv')

In [18]:
driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [9]:
constructor_standings = pd.read_csv('f1db_csv/constructor_standings.csv')

In [13]:
races = pd.read_csv('f1db_csv/races.csv')

In [15]:
races_2023 = races[races['year'] == 2023]

In [16]:
races_2023

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1079,1098,2023,1,3,Bahrain Grand Prix,2023-03-05,15:00:00,https://en.wikipedia.org/wiki/2023_Bahrain_Gra...,2023-03-03,11:30:00,2023-03-03,15:00:00,2023-03-04,11:30:00,2023-03-04,15:00:00,\N,\N
1080,1099,2023,2,77,Saudi Arabian Grand Prix,2023-03-19,17:00:00,https://en.wikipedia.org/wiki/2023_Saudi_Arabi...,2023-03-17,13:30:00,2023-03-17,17:00:00,2023-03-18,13:30:00,2023-03-18,17:00:00,\N,\N
1081,1100,2023,3,1,Australian Grand Prix,2023-04-02,05:00:00,https://en.wikipedia.org/wiki/2023_Australian_...,2023-03-31,01:30:00,2023-03-31,05:00:00,2023-04-01,01:30:00,2023-04-01,05:00:00,\N,\N
1082,1101,2023,4,73,Azerbaijan Grand Prix,2023-04-30,11:00:00,https://en.wikipedia.org/wiki/2023_Azerbaijan_...,2023-04-28,09:30:00,2023-04-29,09:30:00,\N,\N,2023-04-28,13:00:00,2023-04-29,13:30:00
1083,1102,2023,5,79,Miami Grand Prix,2023-05-07,19:30:00,https://en.wikipedia.org/wiki/2023_Miami_Grand...,2023-05-05,18:00:00,2023-05-05,21:30:00,2023-05-06,16:30:00,2023-05-06,20:00:00,\N,\N
1084,1104,2023,6,6,Monaco Grand Prix,2023-05-28,13:00:00,https://en.wikipedia.org/wiki/2023_Monaco_Gran...,2023-05-26,11:30:00,2023-05-26,15:00:00,2023-05-27,10:30:00,2023-05-27,14:00:00,\N,\N
1085,1105,2023,7,4,Spanish Grand Prix,2023-06-04,13:00:00,https://en.wikipedia.org/wiki/2023_Spanish_Gra...,2023-06-02,11:30:00,2023-06-02,15:00:00,2023-06-03,10:30:00,2023-06-03,14:00:00,\N,\N
1086,1106,2023,8,7,Canadian Grand Prix,2023-06-18,18:00:00,https://en.wikipedia.org/wiki/2023_Canadian_Gr...,2023-06-16,17:30:00,2023-06-16,21:00:00,2023-06-17,16:30:00,2023-06-17,20:00:00,\N,\N
1087,1107,2023,9,70,Austrian Grand Prix,2023-07-02,13:00:00,https://en.wikipedia.org/wiki/2023_Austrian_Gr...,2023-06-30,11:30:00,2023-07-01,10:30:00,\N,\N,2023-06-30,15:00:00,2023-07-01,14:30:00
1088,1108,2023,10,9,British Grand Prix,2023-07-09,14:00:00,https://en.wikipedia.org/wiki/2023_British_Gra...,2023-07-07,11:30:00,2023-07-07,15:00:00,2023-07-08,10:30:00,2023-07-08,14:00:00,\N,\N
1089,1109,2023,11,11,Hungarian Grand Prix,2023-07-23,13:00:00,https://en.wikipedia.org/wiki/2023_Hungarian_G...,2023-07-21,11:30:00,2023-07-21,15:00:00,2023-07-22,10:30:00,2023-07-22,14:00:00,\N,\N
1090,1110,2023,12,13,Belgian Grand Prix,2023-07-30,13:00:00,https://en.wikipedia.org/wiki/2023_Belgian_Gra...,2023-07-28,11:30:00,2023-07-29,10:30:00,\N,\N,2023-07-28,15:00:00,2023-07-29,14:30:00
1091,1111,2023,13,39,Dutch Grand Prix,2023-08-27,13:00:00,https://en.wikipedia.org/wiki/2023_Dutch_Grand...,2023-08-25,10:30:00,2023-08-25,14:00:00,2023-08-26,09:30:00,2023-08-26,13:00:00,\N,\N
1092,1112,2023,14,14,Italian Grand Prix,2023-09-03,13:00:00,https://en.wikipedia.org/wiki/2023_Italian_Gra...,2023-09-01,11:30:00,2023-09-01,15:00:00,2023-09-02,10:30:00,2023-09-02,14:00:00,\N,\N
1093,1113,2023,15,15,Singapore Grand Prix,2023-09-17,12:00:00,https://en.wikipedia.org/wiki/2023_Singapore_G...,2023-09-15,09:30:00,2023-09-15,13:00:00,2023-09-16,09:30:00,2023-09-16,13:00:00,\N,\N
1094,1114,2023,16,22,Japanese Grand Prix,2023-09-24,05:00:00,https://en.wikipedia.org/wiki/2023_Japanese_Gr...,2023-09-22,02:30:00,2023-09-22,06:00:00,2023-09-23,02:30:00,2023-09-23,06:00:00,\N,\N
1095,1115,2023,17,78,Qatar Grand Prix,2023-10-08,17:00:00,https://en.wikipedia.org/wiki/2023_Qatar_Grand...,2023-10-06,13:30:00,2023-10-07,13:00:00,\N,\N,2023-10-06,17:00:00,2023-10-07,17:30:00
1096,1116,2023,18,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00
1097,1117,2023,19,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N
1098,1118,2023,20,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00
1099,1119,2023,21,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-16,04:30:00,2023-11-16,08:00:00,2023-11-17,04:30:00,2023-11-17,08:00:00,\N,\N
1100,1120,2023,22,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N

***
*Note raceId = 1103 is not there due to the Imola Grand Prix (Italy) being canceled due to massive flooding.*
***
2023 Race IDs = 1098-1120

### Narrow down driver standings by raceId to 2023 season.

In [28]:
driver_standings_2023 = driver_standings[(driver_standings["raceId"] >= 1098) & (driver_standings["raceId"]<= 1120)]

In [29]:
driver_standings_2023

,driverStandingsId,raceId,driverId,points,position,positionText,wins
33882,72025,1098,857,0.0,20,20,0
33883,72024,1098,844,0.0,19,19,0
33884,72023,1098,839,0.0,18,18,0
33885,72022,1098,846,0.0,17,17,0
33886,72021,1098,855,0.0,16,16,0
...,...,...,...,...,...,...,...
34339,72513,1120,839,58.0,12,12,0
34340,72514,1120,844,206.0,5,5,0
34341,72515,1120,857,97.0,9,9,0
34342,72516,1120,817,6.0,17,17,0
34343,72517,1120,859,2.0,20,20,0

In [31]:
# Merge the driver info with the 2023 standings
driver_standings_2023_names = driver_standings_2023.merge(driver_info[['driverId','code','forename', 'surname']], on='driverId')

In [32]:
driver_standings_2023_names

,driverStandingsId,raceId,driverId,points,position,positionText,wins,code,forename,surname
0,72025,1098,857,0.0,20,20,0,PIA,Oscar,Piastri
1,71905,1099,857,0.0,19,19,0,PIA,Oscar,Piastri
2,71925,1100,857,4.0,13,13,0,PIA,Oscar,Piastri
3,71945,1101,857,4.0,11,11,0,PIA,Oscar,Piastri
4,71965,1102,857,4.0,14,14,0,PIA,Oscar,Piastri
...,...,...,...,...,...,...,...,...,...,...
457,72407,1116,859,2.0,19,19,0,LAW,Liam,Lawson
458,72429,1117,859,2.0,20,20,0,LAW,Liam,Lawson
459,72451,1118,859,2.0,20,20,0,LAW,Liam,Lawson
460,72495,1119,859,2.0,20,20,0,LAW,Liam,Lawson
461,72517,1120,859,2.0,20,20,0,LAW,Liam,Lawson

In [33]:
# Merge the previous DF with name of the race
driver_standings_2023_races = driver_standings_2023_names.merge(races_2023[['raceId', 'name']], on='raceId')

In [34]:
driver_standings_2023_races

,driverStandingsId,raceId,driverId,points,position,positionText,wins,code,forename,surname,name
0,72025,1098,857,0.0,20,20,0,PIA,Oscar,Piastri,Bahrain Grand Prix
1,72024,1098,844,0.0,19,19,0,LEC,Charles,Leclerc,Bahrain Grand Prix
2,72023,1098,839,0.0,18,18,0,OCO,Esteban,Ocon,Bahrain Grand Prix
3,72022,1098,846,0.0,17,17,0,NOR,Lando,Norris,Bahrain Grand Prix
4,72021,1098,855,0.0,16,16,0,ZHO,Guanyu,Zhou,Bahrain Grand Prix
...,...,...,...,...,...,...,...,...,...,...,...
457,72498,1120,4,206.0,4,4,0,ALO,Fernando,Alonso,Abu Dhabi Grand Prix
458,72497,1120,815,285.0,2,2,2,PER,Sergio,Pérez,Abu Dhabi Grand Prix
459,72496,1120,830,575.0,1,1,19,VER,Max,Verstappen,Abu Dhabi Grand Prix
460,72516,1120,817,6.0,17,17,0,RIC,Daniel,Ricciardo,Abu Dhabi Grand Prix
461,72517,1120,859,2.0,20,20,0,LAW,Liam,Lawson,Abu Dhabi Grand Prix

In [38]:
driver_standings_2023_races = driver_standings_2023_races.rename(columns={'name':'circuitName'})

In [39]:
driver_standings_2023_races

,driverStandingsId,raceId,driverId,points,position,positionText,wins,code,forename,surname,circuitName
0,72025,1098,857,0.0,20,20,0,PIA,Oscar,Piastri,Bahrain Grand Prix
1,72024,1098,844,0.0,19,19,0,LEC,Charles,Leclerc,Bahrain Grand Prix
2,72023,1098,839,0.0,18,18,0,OCO,Esteban,Ocon,Bahrain Grand Prix
3,72022,1098,846,0.0,17,17,0,NOR,Lando,Norris,Bahrain Grand Prix
4,72021,1098,855,0.0,16,16,0,ZHO,Guanyu,Zhou,Bahrain Grand Prix
...,...,...,...,...,...,...,...,...,...,...,...
457,72498,1120,4,206.0,4,4,0,ALO,Fernando,Alonso,Abu Dhabi Grand Prix
458,72497,1120,815,285.0,2,2,2,PER,Sergio,Pérez,Abu Dhabi Grand Prix
459,72496,1120,830,575.0,1,1,19,VER,Max,Verstappen,Abu Dhabi Grand Prix
460,72516,1120,817,6.0,17,17,0,RIC,Daniel,Ricciardo,Abu Dhabi Grand Prix
461,72517,1120,859,2.0,20,20,0,LAW,Liam,Lawson,Abu Dhabi Grand Prix

In [53]:
sorted_races = driver_standings_2023_races.sort_values(by=['raceId', 'position'])

In [54]:
sorted_races

,driverStandingsId,raceId,driverId,points,position,positionText,wins,code,forename,surname,circuitName
19,72006,1098,830,25.0,1,1,1,VER,Max,Verstappen,Bahrain Grand Prix
18,72007,1098,815,18.0,2,2,0,PER,Sergio,Pérez,Bahrain Grand Prix
17,72008,1098,4,15.0,3,3,0,ALO,Fernando,Alonso,Bahrain Grand Prix
16,72009,1098,832,12.0,4,4,0,SAI,Carlos,Sainz,Bahrain Grand Prix
15,72010,1098,1,10.0,5,5,0,HAM,Lewis,Hamilton,Bahrain Grand Prix
...,...,...,...,...,...,...,...,...,...,...,...
444,72511,1120,855,6.0,18,18,0,ZHO,Guanyu,Zhou,Abu Dhabi Grand Prix
447,72508,1120,825,3.0,19,19,0,MAG,Kevin,Magnussen,Abu Dhabi Grand Prix
461,72517,1120,859,2.0,20,20,0,LAW,Liam,Lawson,Abu Dhabi Grand Prix
448,72507,1120,858,1.0,21,21,0,SAR,Logan,Sargeant,Abu Dhabi Grand Prix
446,72509,1120,856,0.0,22,22,0,DEV,Nyck,de Vries,Abu Dhabi Grand Prix

In [61]:
sorted_races.set_index('circuitName')

,driverStandingsId,raceId,driverId,points,position,positionText,wins,code,forename,surname
circuitName,,,,,,,,,,
Bahrain Grand Prix,72006,1098,830,25.0,1,1,1,VER,Max,Verstappen
Bahrain Grand Prix,72007,1098,815,18.0,2,2,0,PER,Sergio,Pérez
Bahrain Grand Prix,72008,1098,4,15.0,3,3,0,ALO,Fernando,Alonso
Bahrain Grand Prix,72009,1098,832,12.0,4,4,0,SAI,Carlos,Sainz
Bahrain Grand Prix,72010,1098,1,10.0,5,5,0,HAM,Lewis,Hamilton
...,...,...,...,...,...,...,...,...,...,...
Abu Dhabi Grand Prix,72511,1120,855,6.0,18,18,0,ZHO,Guanyu,Zhou
Abu Dhabi Grand Prix,72508,1120,825,3.0,19,19,0,MAG,Kevin,Magnussen
Abu Dhabi Grand Prix,72517,1120,859,2.0,20,20,0,LAW,Liam,Lawson
Abu Dhabi Grand Prix,72507,1120,858,1.0,21,21,0,SAR,Logan,Sargeant
Abu Dhabi Grand Prix,72509,1120,856,0.0,22,22,0,DEV,Nyck,de Vries

In [ ]:
sorted_races.groupby(['circuitName', '')