## Driver and Constructor Season Totals for the 2023 season.

In [1]:
import pandas as pd

In [2]:
driver_info = pd.read_csv('f1db_csv/drivers.csv')

In [3]:
constructor_info = pd.read_csv('f1db_csv/constructors.csv')

In [4]:
circuit_info = pd.read_csv('f1db_csv/circuits.csv')

In [5]:
driver_info.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [6]:
constructor_info.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [7]:
driver_standings = pd.read_csv('f1db_csv/driver_standings.csv')

In [8]:
driver_standings.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [9]:
constructor_standings = pd.read_csv('f1db_csv/constructor_standings.csv')

In [10]:
races = pd.read_csv('f1db_csv/races.csv')

### Cleaning Race and Sprint Race Data

Below we will clean up the Race and Sprint Race Data, while also merging circuit info through the matching circuit ID, adding location data such as city, country, latitude, and longitude. This will be for the purposes of visualizing on a map just extensive the schedule is in terms of traveling.

In [11]:
races.tail()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [12]:
race_data = races.drop(columns=['url', 'time', 'fp1_date', 'fp1_time', "fp2_date", 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time'])

In [13]:
race_data.head()

   raceId  year  round  circuitId                   name        date
0       1  2009      1          1  Australian Grand Prix  2009-03-29
1       2  2009      2          2   Malaysian Grand Prix  2009-04-05
2       3  2009      3         17     Chinese Grand Prix  2009-04-19
3       4  2009      4          3     Bahrain Grand Prix  2009-04-26
4       5  2009      5          4     Spanish Grand Prix  2009-05-10

In [14]:
circuit_info.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [15]:
race_data = pd.merge(race_data, circuit_info[['circuitId','location', 'country', 'lat', 'lng']], on='circuitId', how='left')

In [16]:
race_data.head(5)

,raceId,year,round,circuitId,name,date,location,country,lat,lng
0,1,2009,1,1,Australian Grand Prix,2009-03-29,Melbourne,Australia,-37.84970,144.96800
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,Kuala Lumpur,Malaysia,2.76083,101.73800
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,Shanghai,China,31.33890,121.22000
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,Sakhir,Bahrain,26.03250,50.51060
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,Montmeló,Spain,41.57000,2.26111

In [17]:
sprint_data = races[['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'sprint_date']]

In [18]:
sprint_data.head()

,raceId,year,round,circuitId,name,date,sprint_date
0,1,2009,1,1,Australian Grand Prix,2009-03-29,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,\N

In [19]:
sprint_data = sprint_data[sprint_data['sprint_date'] != '\\N']

In [20]:
sprint_data = pd.merge(sprint_data, circuit_info[['circuitId','location', 'country', 'lat', 'lng']], on='circuitId', how='left')

In [21]:
sprint_data

,raceId,year,round,circuitId,name,date,sprint_date,location,country,lat,lng
0,1061,2021,10,9,British Grand Prix,2021-07-18,2021-07-17,Silverstone,UK,52.0786,-1.01694
1,1065,2021,14,14,Italian Grand Prix,2021-09-12,2021-09-11,Monza,Italy,45.6156,9.28111
2,1071,2021,19,18,São Paulo Grand Prix,2021-11-14,2021-11-13,São Paulo,Brazil,-23.7036,-46.69970
3,1077,2022,4,21,Emilia Romagna Grand Prix,2022-04-24,2022-04-23,Imola,Italy,44.3439,11.71670
4,1084,2022,11,70,Austrian Grand Prix,2022-07-10,2022-07-09,Spielberg,Austria,47.2197,14.76470
5,1095,2022,21,18,São Paulo Grand Prix,2022-11-13,2022-11-12,São Paulo,Brazil,-23.7036,-46.69970
6,1101,2023,4,73,Azerbaijan Grand Prix,2023-04-30,2023-04-29,Baku,Azerbaijan,40.3725,49.85330
7,1107,2023,9,70,Austrian Grand Prix,2023-07-02,2023-07-01,Spielberg,Austria,47.2197,14.76470
8,1110,2023,12,13,Belgian Grand Prix,2023-07-30,2023-07-29,Spa,Belgium,50.4372,5.97139
9,1115,2023,17,78,Qatar Grand Prix,2023-10-08,2023-10-07,Al Daayen,Qatar,25.4900,51.45420
10,1116,2023,18,69,United States Grand Prix,2023-10-22,2023-10-21,Austin,USA,30.1328,-97.64110
11,1118,2023,20,18,São Paulo Grand Prix,2023-11-05,2023-11-04,São Paulo,Brazil,-23.7036,-46.69970
12,1125,2024,5,17,Chinese Grand Prix,2024-04-21,2024-04-20,Shanghai,China,31.3389,121.22000
13,1126,2024,6,79,Miami Grand Prix,2024-05-05,2024-05-04,Miami,USA,25.9581,-80.23890
14,1131,2024,11,70,Austrian Grand Prix,2024-06-30,2024-06-29,Spielberg,Austria,47.2197,14.76470
15,1139,2024,19,69,United States Grand Prix,2024-10-20,2024-10-19,Austin,USA,30.1328,-97.64110
16,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,2024-11-02,São Paulo,Brazil,-23.7036,-46.69970
17,1143,2024,23,78,Qatar Grand Prix,2024-12-01,2024-11-30,Al Daayen,Qatar,25.4900,51.45420